import axios from "axios";

/*
    Create an endpoint with axios in order to receive client requests and the response 
    are JSON generated by json-server request to db.json
*/
export const apiAxios = axios.create({
    baseURL: 'http://localhost:8001',
});